# Prettier configuration
# why is it so poor? see https://prettier.io/docs/en/option-philosophy.html

overrides:
  - files:
      - "**/*.java"
    options:
      printWidth: 140
      tabWidth: 4
      useTabs: false
      trailingComma: none
